name: Job summary demo

on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo '### Hello world! :roket:' >> $GITHUB_STEP_SUMMARY
      - run: echo '### Love this feature! :medal_sports:' >> $GITHUB_STEP_SUMMARY
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Script
        uses: actions/github-script@v7.0.1
        with:
          script: |
            await core.summary
            .addHeading { 'Test Results' }
            .addTable([
              [{data: 'File', header:true}, {data: 'Result', header:true}],
              ['foo.js', 'Pass ✅'],
              ['bar.js', 'Fail ❌'],
              ['test.js', 'Pass ✅']
            ])
            .addLink('View staging deployment!' , 'https://github.com'),
            .write()
